import type { PolicyRule } from "@/forge/types";

export const policyRules: PolicyRule[] = [
  {
    id: "pdpl-data-handling",
    title: "PDPL Personal Data Handling",
    description: "All personal data processing must have documented consent and purpose limitation before code execution",
    category: "Compliance",
    severity: "Blocking",
    enabled: true,
    applicableFrameworks: ["PDPL"],
  },
  {
    id: "nca-ecc-controls",
    title: "NCA Essential Cybersecurity Controls",
    description: "Security controls must be validated against NCA ECC requirements before deployment",
    category: "Security",
    severity: "Blocking",
    enabled: true,
    applicableFrameworks: ["NCA_ECC"],
  },
  {
    id: "pdpl-data-residency",
    title: "PDPL Data Residency",
    description: "Personal data of Saudi citizens must be stored and processed within Saudi Arabia (me-central2 region)",
    category: "Compliance",
    severity: "Blocking",
    enabled: true,
    applicableFrameworks: ["PDPL", "NDMO"],
  },
  {
    id: "proof-chain-completeness",
    title: "Proof Chain Completeness Threshold",
    description: "Stories cannot advance past the Test phase unless the proof chain completeness is at or above 80%",
    category: "Quality",
    severity: "Blocking",
    enabled: true,
    applicableFrameworks: [],
  },
  {
    id: "code-coverage-threshold",
    title: "Minimum Code Coverage",
    description: "Unit test coverage must be at least 80% before a story can advance from Develop to Test",
    category: "Quality",
    severity: "Blocking",
    enabled: true,
    applicableFrameworks: [],
  },
  {
    id: "sonarqube-quality-gate",
    title: "SonarQube Quality Gate",
    description: "SonarQube quality gate must pass with zero critical or high severity issues before CI proceeds",
    category: "Quality",
    severity: "Advisory",
    enabled: true,
    applicableFrameworks: [],
  },
  {
    id: "nca-mfa-requirement",
    title: "NCA Multi Factor Authentication",
    description: "All citizen facing services and admin portals must implement multi factor authentication as per NCA ECC Control 1.7",
    category: "Security",
    severity: "Blocking",
    enabled: true,
    applicableFrameworks: ["NCA_ECC"],
  },
  {
    id: "nca-encryption-at-rest",
    title: "NCA Encryption at Rest",
    description: "All personal and sensitive data must be encrypted at rest using AES-256 or equivalent as per NCA ECC requirements",
    category: "Security",
    severity: "Blocking",
    enabled: true,
    applicableFrameworks: ["NCA_ECC"],
  },
  {
    id: "pdpl-consent-before-processing",
    title: "PDPL Consent Before Processing",
    description: "Consent records must be stored before any biometric or personal data is processed. Parallel consent recording is not permitted.",
    category: "Compliance",
    severity: "Blocking",
    enabled: true,
    applicableFrameworks: ["PDPL"],
  },
  {
    id: "architecture-review-required",
    title: "Architecture Review for New Service Boundaries",
    description: "Any story introducing a new service boundary or external integration must have a documented architecture impact assessment",
    category: "Quality",
    severity: "Advisory",
    enabled: true,
    applicableFrameworks: [],
  },
  {
    id: "performance-baseline",
    title: "Performance Baseline Required",
    description: "Citizen facing services must complete a load test at 5,000 concurrent users before release gate",
    category: "Performance",
    severity: "Advisory",
    enabled: true,
    applicableFrameworks: [],
  },
  {
    id: "iso-27001-risk-register",
    title: "ISO 27001 Risk Register Update",
    description: "Any story introducing new data processing activities must update the information security risk register",
    category: "Compliance",
    severity: "Info",
    enabled: false,
    applicableFrameworks: ["ISO_27001"],
  },
  {
    id: "accessibility-wcag",
    title: "WCAG 2.1 AA Accessibility",
    description: "All citizen facing UI components must pass WCAG 2.1 AA accessibility audit before release",
    category: "Quality",
    severity: "Advisory",
    enabled: true,
    applicableFrameworks: [],
  },
  {
    id: "dependency-vulnerability-scan",
    title: "Dependency Vulnerability Scan",
    description: "All third party dependencies must pass vulnerability scan with no critical or high CVEs before merge",
    category: "Security",
    severity: "Blocking",
    enabled: true,
    applicableFrameworks: ["NCA_ECC"],
  },
  {
    id: "execution-loop-max-iterations",
    title: "Execution Loop Max Iterations",
    description: "Code execution loop must not exceed the configured maximum number of iterations before human review",
    category: "Quality",
    severity: "Blocking",
    enabled: true,
    applicableFrameworks: [],
  },
  {
    id: "context-budget-hard-ceiling",
    title: "Context Budget Hard Ceiling",
    description: "Context budget allocation must not exceed the hard ceiling without explicit escalation and approval",
    category: "Quality",
    severity: "Blocking",
    enabled: true,
    applicableFrameworks: [],
  },
  {
    id: "merge-requires-human-approval",
    title: "Merge Requires Human Approval",
    description: "All code merges from autonomous execution loops require explicit human approval before deployment",
    category: "Security",
    severity: "Blocking",
    enabled: true,
    applicableFrameworks: ["PDPL", "NCA_ECC"],
  },
  {
    id: "explainability-report-required",
    title: "Explainability Report Required",
    description: "Every autonomous code execution run must produce an explainability report before human review",
    category: "Compliance",
    severity: "Blocking",
    enabled: true,
    applicableFrameworks: ["PDPL"],
  },
  {
    id: "bidirectional-action-audit",
    title: "Bidirectional Action Audit Required",
    description: "All bidirectional connector actions must be logged in the audit trail with governance gate reference",
    category: "Security",
    severity: "Advisory",
    enabled: true,
    applicableFrameworks: ["NCA_ECC"],
  },
  {
    id: "operate-lesson-capture",
    title: "Operate Lesson Capture Required",
    description: "Resolved production incidents must capture lessons learned that flow into the Context Hub",
    category: "Quality",
    severity: "Advisory",
    enabled: true,
    applicableFrameworks: [],
  },
];
