import type { ProjectTemplate } from "@/forge/types";

export const projectTemplates: ProjectTemplate[] = [
  {
    key: "full-sdlc",
    name: "Full SDLC",
    description: "End to end software delivery from planning through release with full governance",
    icon: "Layers3",
    category: "Engineering",
    phases: [
      { id: "plan", name: "Plan", states: ["Pending", "Brief", "Ready Design"] },
      { id: "design", name: "Design", states: ["Designing", "Design Review", "Ready Dev"] },
      { id: "develop", name: "Develop", states: ["Coding", "Testing", "Code Review", "Revisions", "Ready CI"] },
      { id: "test", name: "Test", states: ["CI Running", "CI Pass", "CI Fail"] },
      { id: "ship", name: "Ship", states: ["Shipped", "Released", "Ready Operate"] },
      { id: "operate", name: "Operate", states: ["Monitoring", "Incident Detected", "Investigating", "Remediating", "Learning Captured"] },
    ],
    defaultGates: [
      { fromPhase: "plan", toPhase: "design", approvers: 1, roles: ["delivery-lead", "product-owner"] },
      { fromPhase: "design", toPhase: "develop", approvers: 1, roles: ["solution-architect", "delivery-lead"] },
      { fromPhase: "develop", toPhase: "test", approvers: 1, roles: ["qa-lead", "developer"] },
      { fromPhase: "test", toPhase: "ship", approvers: 2, roles: ["delivery-lead", "cto"] },
      { fromPhase: "ship", toPhase: "operate", approvers: 1, roles: ["devops-lead", "cto"] },
    ],
    recommendedConnectors: ["github", "jira", "github-actions", "sonarqube", "slack"],
    recommendedPersonas: ["cto", "delivery-lead", "solution-architect", "developer", "qa-lead"],
    governancePosture: "Standard",
    complianceDefaults: [],
  },
  {
    key: "data-integration",
    name: "Data Integration",
    description: "Structured pipeline for ingesting, transforming, validating, and deploying data assets",
    icon: "Database",
    category: "Engineering",
    phases: [
      { id: "ingest", name: "Ingest", states: ["Source Identified", "Schema Mapped", "Ready Transform"] },
      { id: "transform", name: "Transform", states: ["Transforming", "Quality Check", "Ready Validate"] },
      { id: "validate", name: "Validate", states: ["Validating", "Validation Pass", "Validation Fail"] },
      { id: "deploy", name: "Deploy", states: ["Deploying", "Live", "Archived"] },
    ],
    defaultGates: [
      { fromPhase: "ingest", toPhase: "transform", approvers: 1, roles: ["solution-architect", "devops-lead"] },
      { fromPhase: "transform", toPhase: "validate", approvers: 1, roles: ["qa-lead", "solution-architect"] },
      { fromPhase: "validate", toPhase: "deploy", approvers: 2, roles: ["delivery-lead", "security-officer"] },
    ],
    recommendedConnectors: ["github", "github-actions", "sonarqube", "gcp", "slack"],
    recommendedPersonas: ["solution-architect", "devops-lead", "qa-lead", "delivery-lead"],
    governancePosture: "Standard",
    complianceDefaults: [],
  },
  {
    key: "api-development",
    name: "API Development",
    description: "Design first API delivery from specification through testing to publication",
    icon: "Zap",
    category: "Engineering",
    phases: [
      { id: "design", name: "Design", states: ["Spec Draft", "Spec Review", "Spec Approved"] },
      { id: "build", name: "Build", states: ["Building", "Unit Tests", "Integration Tests", "Ready Review"] },
      { id: "test", name: "Test", states: ["QA Running", "Security Scan", "Performance Test", "Approved"] },
      { id: "publish", name: "Publish", states: ["Published", "Versioned", "Deprecated"] },
    ],
    defaultGates: [
      { fromPhase: "design", toPhase: "build", approvers: 1, roles: ["solution-architect", "product-owner"] },
      { fromPhase: "build", toPhase: "test", approvers: 1, roles: ["qa-lead", "developer"] },
      { fromPhase: "test", toPhase: "publish", approvers: 2, roles: ["security-officer", "delivery-lead"] },
    ],
    recommendedConnectors: ["github", "github-actions", "sonarqube", "slack", "azure-devops"],
    recommendedPersonas: ["developer", "solution-architect", "qa-lead", "security-officer"],
    governancePosture: "Standard",
    complianceDefaults: [],
  },
  {
    key: "mobile-app",
    name: "Mobile Application",
    description: "Native or cross platform mobile app delivery with UX review and store submission",
    icon: "Smartphone",
    category: "Engineering",
    phases: [
      { id: "plan", name: "Plan", states: ["Requirements", "Wireframes", "Ready Design"] },
      { id: "design", name: "Design", states: ["UI Design", "Prototype", "Design Approved"] },
      { id: "build", name: "Build", states: ["Building", "Unit Tests", "Device Testing"] },
      { id: "test", name: "Test", states: ["QA Pass", "Accessibility Review", "Approved"] },
      { id: "release", name: "Release", states: ["Submitted", "Store Review", "Live"] },
    ],
    defaultGates: [
      { fromPhase: "plan", toPhase: "design", approvers: 1, roles: ["product-owner", "delivery-lead"] },
      { fromPhase: "design", toPhase: "build", approvers: 1, roles: ["solution-architect", "delivery-lead"] },
      { fromPhase: "build", toPhase: "test", approvers: 1, roles: ["qa-lead"] },
      { fromPhase: "test", toPhase: "release", approvers: 2, roles: ["delivery-lead", "cto"] },
    ],
    recommendedConnectors: ["github", "github-actions", "slack", "jira"],
    recommendedPersonas: ["developer", "qa-lead", "product-owner", "delivery-lead"],
    governancePosture: "Standard",
    complianceDefaults: [],
  },
  {
    key: "platform-engineering",
    name: "Platform Engineering",
    description: "Infrastructure, tooling, and internal developer platform design and provisioning",
    icon: "Server",
    category: "Engineering",
    phases: [
      { id: "design", name: "Design", states: ["Architecture Draft", "Capacity Plan", "Design Approved"] },
      { id: "provision", name: "Provision", states: ["Provisioning", "Configuration", "Ready Test"] },
      { id: "operate", name: "Operate", states: ["Live", "Monitored", "Stable"] },
    ],
    defaultGates: [
      { fromPhase: "design", toPhase: "provision", approvers: 2, roles: ["solution-architect", "security-officer"] },
      { fromPhase: "provision", toPhase: "operate", approvers: 2, roles: ["devops-lead", "cto"] },
    ],
    recommendedConnectors: ["github", "argocd", "gcp", "aws", "azure", "slack"],
    recommendedPersonas: ["devops-lead", "solution-architect", "security-officer", "cto"],
    governancePosture: "Enhanced",
    complianceDefaults: [],
  },
  {
    key: "gov-digital-service",
    name: "Government Digital Service",
    description: "Saudi government portal or service delivery with PDPL compliance and dual approval gates",
    icon: "Landmark",
    category: "Saudi Market",
    phases: [
      { id: "directive", name: "Directive", states: ["Ministerial Brief", "Scope Defined", "Ready Analysis"] },
      { id: "analysis", name: "Analysis", states: ["Requirements", "PDPL Impact", "NCA Review", "Ready Design"] },
      { id: "design", name: "Design", states: ["Architecture", "Security Design", "UX Design", "Ready Build"] },
      { id: "build", name: "Build", states: ["Coding", "Unit Tests", "Integration Tests", "Ready Test"] },
      { id: "test", name: "Test", states: ["QA Pass", "Security Audit", "Nafath Integration Test"] },
      { id: "compliance", name: "Compliance", states: ["PDPL Verification", "NCA ECC Check", "NDMO Clearance", "Approved"] },
      { id: "release", name: "Release", states: ["Staged", "Ministerial Sign Off", "Live"] },
    ],
    defaultGates: [
      { fromPhase: "directive", toPhase: "analysis", approvers: 1, roles: ["programme-director", "product-owner"] },
      { fromPhase: "analysis", toPhase: "design", approvers: 2, roles: ["compliance-officer", "security-officer"] },
      { fromPhase: "design", toPhase: "build", approvers: 2, roles: ["solution-architect", "security-officer"] },
      { fromPhase: "build", toPhase: "test", approvers: 1, roles: ["qa-lead", "delivery-lead"] },
      { fromPhase: "test", toPhase: "compliance", approvers: 2, roles: ["compliance-officer", "security-officer"] },
      { fromPhase: "compliance", toPhase: "release", approvers: 2, roles: ["programme-director", "cto"] },
    ],
    recommendedConnectors: ["github", "jira", "github-actions", "sonarqube", "pdpl-scanner", "nca-ecc", "slack", "email"],
    recommendedPersonas: ["cto", "programme-director", "compliance-officer", "security-officer", "solution-architect", "delivery-lead"],
    governancePosture: "Maximum",
    complianceDefaults: ["PDPL", "NCA_ECC", "NDMO"],
  },
  {
    key: "smart-city",
    name: "Smart City Platform",
    description: "Urban intelligence platform integrating IoT, mobility, and citizen services for NEOM and Vision 2030",
    icon: "Globe",
    category: "Saudi Market",
    phases: [
      { id: "vision", name: "Vision", states: ["Vision Defined", "Feasibility", "Ready Architecture"] },
      { id: "architecture", name: "Architecture", states: ["System Design", "Integration Map", "Security Architecture", "Approved"] },
      { id: "build", name: "Build", states: ["Core Build", "IoT Integration", "Data Pipeline", "Ready Test"] },
      { id: "integrate", name: "Integrate", states: ["Third Party", "Government Systems", "Nafath SSO", "Ready Test"] },
      { id: "test", name: "Test", states: ["Load Test", "Security Penetration", "Citizen Simulation", "Approved"] },
      { id: "operate", name: "Operate", states: ["Pilot Live", "Full Rollout", "Stable"] },
    ],
    defaultGates: [
      { fromPhase: "vision", toPhase: "architecture", approvers: 2, roles: ["cto", "programme-director"] },
      { fromPhase: "architecture", toPhase: "build", approvers: 2, roles: ["solution-architect", "security-officer"] },
      { fromPhase: "build", toPhase: "integrate", approvers: 1, roles: ["devops-lead", "solution-architect"] },
      { fromPhase: "integrate", toPhase: "test", approvers: 1, roles: ["qa-lead", "security-officer"] },
      { fromPhase: "test", toPhase: "operate", approvers: 2, roles: ["cto", "programme-director"] },
    ],
    recommendedConnectors: ["github", "gcp", "aws", "slack", "pdpl-scanner", "nca-ecc"],
    recommendedPersonas: ["cto", "programme-director", "solution-architect", "devops-lead", "security-officer"],
    governancePosture: "Enhanced",
    complianceDefaults: ["PDPL", "NCA_ECC"],
  },
  {
    key: "compliance-transformation",
    name: "Compliance Transformation",
    description: "Structured programme to assess, map, implement, and certify against Saudi regulatory frameworks",
    icon: "ShieldCheck",
    category: "Saudi Market",
    phases: [
      { id: "assess", name: "Assess", states: ["Gap Analysis", "Risk Register", "Baseline Report"] },
      { id: "map", name: "Map", states: ["Control Mapping", "Evidence Requirements", "Roadmap Defined"] },
      { id: "implement", name: "Implement", states: ["Controls Implemented", "Evidence Collected", "Audit Trail Ready"] },
      { id: "certify", name: "Certify", states: ["Internal Review", "External Audit", "Certified"] },
    ],
    defaultGates: [
      { fromPhase: "assess", toPhase: "map", approvers: 2, roles: ["compliance-officer", "security-officer"] },
      { fromPhase: "map", toPhase: "implement", approvers: 2, roles: ["compliance-officer", "programme-director"] },
      { fromPhase: "implement", toPhase: "certify", approvers: 2, roles: ["compliance-officer", "cto"] },
    ],
    recommendedConnectors: ["pdpl-scanner", "nca-ecc", "iso-mapper", "email", "slack"],
    recommendedPersonas: ["compliance-officer", "security-officer", "programme-director", "cto"],
    governancePosture: "Maximum",
    complianceDefaults: ["PDPL", "NCA_ECC", "ISO_27001", "NDMO"],
  },
  {
    key: "custom",
    name: "Custom",
    description: "Start from scratch with a fully configurable workflow, governance posture, and connector set",
    icon: "PenTool",
    category: "Custom",
    phases: [
      { id: "phase-1", name: "Phase 1", states: ["Pending", "In Progress", "Done"] },
    ],
    defaultGates: [
      { fromPhase: "phase-1", toPhase: "phase-1", approvers: 1, roles: ["delivery-lead"] },
    ],
    recommendedConnectors: [],
    recommendedPersonas: ["delivery-lead"],
    governancePosture: "Standard",
    complianceDefaults: [],
  },
  {
    key: "ai-accelerated",
    name: "AI Accelerated",
    description: "Full SDLC with autonomous code generation, supervised execution loops, and operational learning capture",
    icon: "Zap",
    category: "Engineering",
    phases: [
      { id: "plan", name: "Plan", states: ["Pending", "Brief", "Ready Design"] },
      { id: "design", name: "Design", states: ["Designing", "Design Review", "Ready Dev"] },
      { id: "develop", name: "Develop", states: ["Coding", "Agent Generation", "Test", "Review", "Ready CI"] },
      { id: "test", name: "Test", states: ["CI Running", "CI Pass", "CI Fail"] },
      { id: "ship", name: "Ship", states: ["Shipped", "Released", "Ready Operate"] },
      { id: "operate", name: "Operate", states: ["Monitoring", "Incident Detected", "Investigating", "Remediating", "Learning Captured"] },
    ],
    defaultGates: [
      { fromPhase: "plan", toPhase: "design", approvers: 1, roles: ["delivery-lead", "product-owner"] },
      { fromPhase: "design", toPhase: "develop", approvers: 1, roles: ["solution-architect", "delivery-lead"] },
      { fromPhase: "develop", toPhase: "test", approvers: 1, roles: ["qa-lead", "developer"] },
      { fromPhase: "test", toPhase: "ship", approvers: 2, roles: ["delivery-lead", "cto"] },
      { fromPhase: "ship", toPhase: "operate", approvers: 1, roles: ["devops-lead", "cto"] },
    ],
    recommendedConnectors: ["github", "jira", "github-actions", "sonarqube", "slack", "gcp"],
    recommendedPersonas: ["cto", "delivery-lead", "solution-architect", "developer", "qa-lead", "devops-lead"],
    governancePosture: "Enhanced",
    complianceDefaults: ["PDPL", "NCA_ECC"],
  },
];
