import type { AuditEvent } from "@/forge/types";

export const auditEvents: AuditEvent[] = [
  {
    id: "audit-1",
    type: "state-change",
    title: "Story advanced to Design phase",
    detail: "Citizen Authentication Service moved from Plan to Design. All plan gate criteria satisfied.",
    actor: "Sara Malik",
    actorRole: "Delivery Lead",
    timestamp: "April 20, 2026 14:32",
    proofHash: "7f3a2b1c",
    relatedStoryId: "forge-story-1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-2",
    type: "approval",
    title: "Design gate approved",
    detail: "Architecture review gate passed. Sara Malik and Ahmad Karimi approved the design transition.",
    actor: "Sara Malik",
    actorRole: "Solution Architect",
    timestamp: "April 20, 2026 16:45",
    proofHash: "a8f2c4d1",
    relatedStoryId: "forge-story-1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-3",
    type: "ai-action",
    title: "AI Agent generated architecture impact assessment",
    detail: "Context compilation across 4 projects. 23 reusable patterns identified. Confidence score: 91%.",
    actor: "Forge AI Agent",
    actorRole: "AI System",
    timestamp: "April 20, 2026 09:12",
    proofHash: "3b1e7f9a",
    relatedStoryId: "forge-story-1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-4",
    type: "state-change",
    title: "Story advanced to Build phase",
    detail: "Citizen Authentication Service moved from Design to Build. Architecture and security design gates cleared.",
    actor: "Omar Rahman",
    actorRole: "Developer",
    timestamp: "April 20, 2026 18:00",
    proofHash: "c9d2e4f7",
    relatedStoryId: "forge-story-1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-5",
    type: "connector-event",
    title: "GitHub PR #42 opened",
    detail: "Citizen Authentication Service with Nafath SSO. 12 files changed, 847 additions, 23 deletions.",
    actor: "Omar Rahman",
    actorRole: "Developer",
    timestamp: "April 22, 2026 09:00",
    proofHash: "f1a3b5c7",
    relatedStoryId: "forge-story-1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-6",
    type: "connector-event",
    title: "CI pipeline passed on feature/citizen-auth",
    detail: "All 87 tests passed. SonarQube quality gate passed. PDPL compliance scan clear. Coverage: 94.2%.",
    actor: "GitHub Actions",
    actorRole: "CI System",
    timestamp: "April 22, 2026 09:14",
    proofHash: "d4e6f8a0",
    relatedStoryId: "forge-story-1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-7",
    type: "evidence-generated",
    title: "PDPL evidence pack generated",
    detail: "12 evidence items compiled into PDPL compliance pack. Proof chain completeness: 94%.",
    actor: "Dana Youssef",
    actorRole: "Compliance Officer",
    timestamp: "April 22, 2026 10:30",
    proofHash: "e5f7a9b1",
    relatedStoryId: "forge-story-1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-8",
    type: "approval",
    title: "Compliance gate approved",
    detail: "PDPL and NCA ECC compliance verified. Dana Youssef and Khalid Al Rashid approved.",
    actor: "Dana Youssef",
    actorRole: "Compliance Officer",
    timestamp: "April 21, 2026 15:22",
    proofHash: "f6a8b0c2",
    relatedStoryId: "forge-story-1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-9",
    type: "config-change",
    title: "GitHub connector connected",
    detail: "GitHub integration configured for ndpp project. Repository: TheArkitektai/arkitekt-forge-demo. 42 commits synced.",
    actor: "Adel Sami",
    actorRole: "DevOps Lead",
    timestamp: "April 18, 2026 11:00",
    proofHash: "a1b3c5d7",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-10",
    type: "config-change",
    title: "PDPL compliance scanner enabled",
    detail: "PDPL Compliance Scanner connector activated. Scanning every 30 minutes. First scan completed with 0 findings.",
    actor: "Dana Youssef",
    actorRole: "Compliance Officer",
    timestamp: "April 18, 2026 11:45",
    proofHash: "b2c4d6e8",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-11",
    type: "ai-action",
    title: "AI Agent generated story brief",
    detail: "Story brief for Citizen Authentication Service generated. 142 memory artifacts analysed. 7 patterns applied.",
    actor: "Forge AI Agent",
    actorRole: "AI System",
    timestamp: "April 19, 2026 08:30",
    proofHash: "c3d5e7f9",
    relatedStoryId: "forge-story-1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-12",
    type: "approval",
    title: "Release gate approved",
    detail: "Final release gate cleared. Story approved for deployment by Omar Rahman and Sara Malik.",
    actor: "Sara Malik",
    actorRole: "Solution Architect",
    timestamp: "April 22, 2026 11:00",
    proofHash: "d4e6f8g0",
    relatedStoryId: "forge-story-1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-13",
    type: "state-change",
    title: "Story advanced to Test phase",
    detail: "Citizen Authentication Service moved from Build to Test. Code review approved by 2 reviewers.",
    actor: "Reem Al Saud",
    actorRole: "QA Lead",
    timestamp: "April 21, 2026 10:00",
    proofHash: "e5f7g9h1",
    relatedStoryId: "forge-story-1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-14",
    type: "state-change",
    title: "Story advanced to Compliance phase",
    detail: "Citizen Authentication Service moved from Test to Compliance. All test gates satisfied.",
    actor: "Reem Al Saud",
    actorRole: "QA Lead",
    timestamp: "April 21, 2026 13:00",
    proofHash: "f6g8h0i2",
    relatedStoryId: "forge-story-1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-15",
    type: "connector-event",
    title: "SonarQube quality gate passed",
    detail: "Code quality analysis complete. Coverage 94.2%, 0 critical issues, 0 high issues, 2 minor code smells.",
    actor: "SonarQube",
    actorRole: "Quality System",
    timestamp: "April 22, 2026 09:16",
    proofHash: "g7h9i1j3",
    relatedStoryId: "forge-story-1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-16",
    type: "evidence-generated",
    title: "NCA ECC control verification report generated",
    detail: "96% NCA ECC alignment. All critical controls satisfied. One medium advisory documented.",
    actor: "Khalid Al Rashid",
    actorRole: "Security Officer",
    timestamp: "April 21, 2026 14:00",
    proofHash: "h8i0j2k4",
    relatedStoryId: "forge-story-1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-17",
    type: "config-change",
    title: "Policy: PDPL Personal Data Handling updated to Blocking severity",
    detail: "Policy severity changed from Advisory to Blocking for the ndpp project. All new stories must satisfy this policy before advancing to Build.",
    actor: "Dana Youssef",
    actorRole: "Compliance Officer",
    timestamp: "April 17, 2026 09:00",
    proofHash: "i9j1k3l5",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-18",
    type: "ai-action",
    title: "AI Agent completed governance readiness check",
    detail: "Governance check identified 3 outstanding evidence items. Estimated gate readiness: 3 working days.",
    actor: "Forge AI Agent",
    actorRole: "AI System",
    timestamp: "April 20, 2026 15:00",
    proofHash: "j0k2l4m6",
    relatedStoryId: "forge-story-1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-19",
    type: "approval",
    title: "Test gate approved",
    detail: "QA gate cleared. 87 tests passed, coverage 94.2%, accessibility review complete.",
    actor: "Reem Al Saud",
    actorRole: "QA Lead",
    timestamp: "April 21, 2026 12:45",
    proofHash: "k1l3m5n7",
    relatedStoryId: "forge-story-1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-20",
    type: "evidence-generated",
    title: "Architecture impact assessment published to proof chain",
    detail: "Architecture assessment for Citizen Authentication Service written to proof chain. Proof hash: 7f3a2b1c.",
    actor: "Sara Malik",
    actorRole: "Solution Architect",
    timestamp: "April 20, 2026 10:15",
    proofHash: "7f3a2b1c",
    relatedStoryId: "forge-story-1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-21",
    type: "state-change",
    title: "Project: Citizen Identity Gateway advanced to Ship phase",
    detail: "All delivery stories completed. Release confidence 97%. Deployment approved for April 23.",
    actor: "Omar Rahman",
    actorRole: "Delivery Lead",
    timestamp: "April 22, 2026 08:00",
    proofHash: "l2m4n6o8",
    relatedProjectId: "citizen-id",
  },
  {
    id: "audit-22",
    type: "connector-event",
    title: "Slack: Release notification sent to #ndpp-delivery",
    detail: "Automated notification sent. Message: Release 24.4 governance gate cleared. Deployment window: April 23 02:00 AST.",
    actor: "Slack Connector",
    actorRole: "Integration",
    timestamp: "April 22, 2026 11:05",
    proofHash: "m3n5o7p9",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-23",
    type: "state-change",
    title: "Incident detected: Identity Service authentication timeout spike",
    detail: "Critical incident declared. Connection pool exhaustion under concurrent load. Assigned to Omar Al Rashid.",
    actor: "GCP Monitoring",
    actorRole: "System",
    timestamp: "March 20, 2024 08:14",
    proofHash: "n4o6p8q0",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-24",
    type: "state-change",
    title: "Incident resolved: Policy Engine rule evaluation delay",
    detail: "Missing index added to cache table. Query performance restored. Lesson captured for schema migration checklist.",
    actor: "Fatima Hassan",
    actorRole: "SRE",
    timestamp: "March 19, 2024 15:10",
    proofHash: "o5p7q9r1",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-25",
    type: "ai-action",
    title: "Lesson captured from production incident",
    detail: "Schema migrations must include index verification checklist in governance gate. Pattern stored in Context Hub.",
    actor: "Forge Agent",
    actorRole: "AI Agent",
    timestamp: "March 19, 2024 15:15",
    proofHash: "p6q8r0s2",
    relatedProjectId: "ndpp",
  },
  {
    id: "audit-26",
    type: "connector-event",
    title: "Remediation triggered: restart pod via GCP connector",
    detail: "Auto remediation executed on Identity Service pod. Governance gate: Operate Gate. Approval: auto approved (severity below threshold).",
    actor: "GCP Connector",
    actorRole: "Integration",
    timestamp: "March 20, 2024 08:40",
    proofHash: "q7r9s1t3",
    relatedProjectId: "ndpp",
  },
];
