import type { GitHubCommit, GitHubFileNode, GitHubPullRequest, GitHubRepo } from "@/forge/types";

export const GITHUB_BASE_URL = "https://github.com/TheArkitektai/Forge";

export const demoRepo: GitHubRepo = {
  owner: "TheArkitektai",
  name: "Forge",
  url: GITHUB_BASE_URL,
  defaultBranch: "main",
  branches: ["main", "develop", "feature/citizen-auth", "feature/nafath-integration", "feature/pdpl-consent", "release/24.4"],
  lastPush: "2 hours ago",
};

export const demoCommits: GitHubCommit[] = [
  {
    sha: "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0",
    shortSha: "a1b2c3d",
    message: "feat: implement Nafath identity verification flow",
    author: "Omar Rahman",
    timestamp: "2 hours ago",
    filesChanged: 12,
    additions: 847,
    deletions: 23,
    branch: "feature/nafath-integration",
    url: `${GITHUB_BASE_URL}/commit/a1b2c3d`,
  },
  {
    sha: "b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1",
    shortSha: "b2c3d4e",
    message: "fix: add exponential backoff to Nafath retry logic",
    author: "Omar Rahman",
    timestamp: "1 hour ago",
    filesChanged: 2,
    additions: 34,
    deletions: 8,
    branch: "feature/nafath-integration",
    url: `${GITHUB_BASE_URL}/commit/b2c3d4e`,
  },
  {
    sha: "c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2",
    shortSha: "c3d4e5f",
    message: "feat: PDPL consent manager with audit trail integration",
    author: "Dana Youssef",
    timestamp: "4 hours ago",
    filesChanged: 6,
    additions: 312,
    deletions: 0,
    branch: "feature/pdpl-consent",
    url: `${GITHUB_BASE_URL}/commit/c3d4e5f`,
  },
  {
    sha: "d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3",
    shortSha: "d4e5f6a",
    message: "test: add integration tests for citizen authentication flow",
    author: "Reem Al Saud",
    timestamp: "5 hours ago",
    filesChanged: 8,
    additions: 423,
    deletions: 12,
    branch: "feature/citizen-auth",
    url: `${GITHUB_BASE_URL}/commit/d4e5f6a`,
  },
  {
    sha: "e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4",
    shortSha: "e5f6a7b",
    message: "chore: update NCA ECC control checklist to v2.3",
    author: "Khalid Al Rashid",
    timestamp: "6 hours ago",
    filesChanged: 3,
    additions: 89,
    deletions: 45,
    branch: "develop",
    url: `${GITHUB_BASE_URL}/commit/e5f6a7b`,
  },
  {
    sha: "f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5",
    shortSha: "f6a7b8c",
    message: "feat: session management with 256-bit token entropy",
    author: "Omar Rahman",
    timestamp: "8 hours ago",
    filesChanged: 4,
    additions: 156,
    deletions: 67,
    branch: "feature/citizen-auth",
    url: `${GITHUB_BASE_URL}/commit/f6a7b8c`,
  },
  {
    sha: "a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6",
    shortSha: "a7b8c9d",
    message: "docs: architecture impact assessment for citizen auth service",
    author: "Sara Malik",
    timestamp: "1 day ago",
    filesChanged: 2,
    additions: 234,
    deletions: 0,
    branch: "develop",
    url: `${GITHUB_BASE_URL}/commit/a7b8c9d`,
  },
  {
    sha: "b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7",
    shortSha: "b8c9d0e",
    message: "feat: API routes for identity verification endpoints",
    author: "Omar Rahman",
    timestamp: "1 day ago",
    filesChanged: 5,
    additions: 289,
    deletions: 34,
    branch: "feature/citizen-auth",
    url: `${GITHUB_BASE_URL}/commit/b8c9d0e`,
  },
  {
    sha: "c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8",
    shortSha: "c9d0e1f",
    message: "ci: add PDPL compliance scan to GitHub Actions workflow",
    author: "Adel Sami",
    timestamp: "2 days ago",
    filesChanged: 2,
    additions: 67,
    deletions: 0,
    branch: "main",
    url: `${GITHUB_BASE_URL}/commit/c9d0e1f`,
  },
  {
    sha: "d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9",
    shortSha: "d0e1f2a",
    message: "refactor: extract Nafath provider from auth module",
    author: "Omar Rahman",
    timestamp: "2 days ago",
    filesChanged: 7,
    additions: 198,
    deletions: 187,
    branch: "feature/nafath-integration",
    url: `${GITHUB_BASE_URL}/commit/d0e1f2a`,
  },
  {
    sha: "e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0",
    shortSha: "e1f2a3b",
    message: "feat: ministerial design system integration with Arabic font support",
    author: "Maha Noor",
    timestamp: "3 days ago",
    filesChanged: 9,
    additions: 445,
    deletions: 23,
    branch: "develop",
    url: `${GITHUB_BASE_URL}/commit/e1f2a3b`,
  },
  {
    sha: "f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1",
    shortSha: "f2a3b4c",
    message: "test: unit tests for PDPL consent flow validation",
    author: "Dana Youssef",
    timestamp: "3 days ago",
    filesChanged: 4,
    additions: 312,
    deletions: 0,
    branch: "feature/pdpl-consent",
    url: `${GITHUB_BASE_URL}/commit/f2a3b4c`,
  },
  {
    sha: "a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2",
    shortSha: "a3b4c5d",
    message: "chore: release 24.4 branch cut from develop",
    author: "Sara Malik",
    timestamp: "4 days ago",
    filesChanged: 1,
    additions: 0,
    deletions: 0,
    branch: "release/24.4",
    url: `${GITHUB_BASE_URL}/commit/a3b4c5d`,
  },
  {
    sha: "b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3",
    shortSha: "b4c5d6e",
    message: "fix: session expiry notification for PDPL Article 17 compliance",
    author: "Dana Youssef",
    timestamp: "4 days ago",
    filesChanged: 3,
    additions: 78,
    deletions: 12,
    branch: "feature/citizen-auth",
    url: `${GITHUB_BASE_URL}/commit/b4c5d6e`,
  },
  {
    sha: "c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4",
    shortSha: "c5d6e7f",
    message: "docs: PDPL data flow mapping for citizen authentication",
    author: "Dana Youssef",
    timestamp: "5 days ago",
    filesChanged: 2,
    additions: 189,
    deletions: 0,
    branch: "develop",
    url: `${GITHUB_BASE_URL}/commit/c5d6e7f`,
  },
];

export const demoPullRequests: GitHubPullRequest[] = [
  {
    number: 42,
    title: "feat: Citizen Authentication Service with Nafath SSO",
    author: "Omar Rahman",
    status: "open",
    reviewStatus: "pending",
    branch: "feature/citizen-auth",
    targetBranch: "develop",
    timestamp: "3 hours ago",
    checks: [
      { name: "Unit Tests", status: "passed" },
      { name: "Integration Tests", status: "passed" },
      { name: "SonarQube Analysis", status: "passed" },
      { name: "PDPL Compliance Scan", status: "passed" },
      { name: "Security Review", status: "running" },
    ],
    url: `${GITHUB_BASE_URL}/pull/42`,
  },
  {
    number: 41,
    title: "feat: PDPL consent manager and audit trail",
    author: "Dana Youssef",
    status: "open",
    reviewStatus: "approved",
    branch: "feature/pdpl-consent",
    targetBranch: "develop",
    timestamp: "5 hours ago",
    checks: [
      { name: "Unit Tests", status: "passed" },
      { name: "Integration Tests", status: "passed" },
      { name: "SonarQube Analysis", status: "passed" },
      { name: "PDPL Compliance Scan", status: "passed" },
      { name: "Security Review", status: "passed" },
    ],
    url: `${GITHUB_BASE_URL}/pull/41`,
  },
  {
    number: 40,
    title: "feat: Nafath identity provider with session management",
    author: "Omar Rahman",
    status: "merged",
    reviewStatus: "approved",
    branch: "feature/nafath-integration",
    targetBranch: "develop",
    timestamp: "1 day ago",
    checks: [
      { name: "Unit Tests", status: "passed" },
      { name: "Integration Tests", status: "passed" },
      { name: "SonarQube Analysis", status: "passed" },
      { name: "PDPL Compliance Scan", status: "passed" },
      { name: "Security Review", status: "passed" },
    ],
    url: `${GITHUB_BASE_URL}/pull/40`,
  },
  {
    number: 39,
    title: "ci: PDPL and NCA ECC scanning in deployment pipeline",
    author: "Adel Sami",
    status: "merged",
    reviewStatus: "approved",
    branch: "feature/ci-compliance-scans",
    targetBranch: "main",
    timestamp: "2 days ago",
    checks: [
      { name: "Unit Tests", status: "passed" },
      { name: "Pipeline Validation", status: "passed" },
    ],
    url: `${GITHUB_BASE_URL}/pull/39`,
  },
  {
    number: 38,
    title: "feat: ministerial design system with bilingual support",
    author: "Maha Noor",
    status: "merged",
    reviewStatus: "approved",
    branch: "feature/design-system",
    targetBranch: "develop",
    timestamp: "3 days ago",
    checks: [
      { name: "Unit Tests", status: "passed" },
      { name: "Accessibility Audit", status: "passed" },
      { name: "Visual Regression", status: "passed" },
    ],
    url: `${GITHUB_BASE_URL}/pull/38`,
  },
  {
    number: 37,
    title: "fix: session expiry notification for PDPL compliance",
    author: "Dana Youssef",
    status: "merged",
    reviewStatus: "approved",
    branch: "fix/session-expiry-notification",
    targetBranch: "feature/citizen-auth",
    timestamp: "4 days ago",
    checks: [
      { name: "Unit Tests", status: "passed" },
      { name: "PDPL Compliance Scan", status: "passed" },
    ],
    url: `${GITHUB_BASE_URL}/pull/37`,
  },
];

export const demoFileTree: GitHubFileNode[] = [
  {
    name: "src",
    path: "src",
    type: "directory",
    children: [
      {
        name: "auth",
        path: "src/auth",
        type: "directory",
        children: [
          { name: "NafathProvider.ts", path: "src/auth/NafathProvider.ts", type: "file", language: "typescript", size: "4.2 KB" },
          { name: "SessionManager.ts", path: "src/auth/SessionManager.ts", type: "file", language: "typescript", size: "3.8 KB" },
          { name: "PDPLConsentFlow.ts", path: "src/auth/PDPLConsentFlow.ts", type: "file", language: "typescript", size: "2.1 KB" },
          { name: "types.ts", path: "src/auth/types.ts", type: "file", language: "typescript", size: "1.4 KB" },
        ],
      },
      {
        name: "api",
        path: "src/api",
        type: "directory",
        children: [
          { name: "routes.ts", path: "src/api/routes.ts", type: "file", language: "typescript", size: "6.7 KB" },
          { name: "middleware.ts", path: "src/api/middleware.ts", type: "file", language: "typescript", size: "3.2 KB" },
          { name: "validators.ts", path: "src/api/validators.ts", type: "file", language: "typescript", size: "2.8 KB" },
        ],
      },
      {
        name: "governance",
        path: "src/governance",
        type: "directory",
        children: [
          { name: "ProofChain.ts", path: "src/governance/ProofChain.ts", type: "file", language: "typescript", size: "5.1 KB" },
          { name: "EvidenceCollector.ts", path: "src/governance/EvidenceCollector.ts", type: "file", language: "typescript", size: "3.4 KB" },
          { name: "AuditLogger.ts", path: "src/governance/AuditLogger.ts", type: "file", language: "typescript", size: "2.7 KB" },
        ],
      },
      {
        name: "context",
        path: "src/context",
        type: "directory",
        children: [
          { name: "MemoryGraph.ts", path: "src/context/MemoryGraph.ts", type: "file", language: "typescript", size: "7.2 KB" },
          { name: "PatternMatcher.ts", path: "src/context/PatternMatcher.ts", type: "file", language: "typescript", size: "4.6 KB" },
        ],
      },
      {
        name: "tests",
        path: "src/tests",
        type: "directory",
        children: [
          { name: "auth.test.ts", path: "src/tests/auth.test.ts", type: "file", language: "typescript", size: "8.3 KB" },
          { name: "pdpl.test.ts", path: "src/tests/pdpl.test.ts", type: "file", language: "typescript", size: "5.6 KB" },
          { name: "governance.test.ts", path: "src/tests/governance.test.ts", type: "file", language: "typescript", size: "4.2 KB" },
          { name: "integration.test.ts", path: "src/tests/integration.test.ts", type: "file", language: "typescript", size: "12.1 KB" },
        ],
      },
    ],
  },
  {
    name: "docs",
    path: "docs",
    type: "directory",
    children: [
      { name: "architecture.md", path: "docs/architecture.md", type: "file", language: "markdown", size: "12 KB" },
      {
        name: "compliance",
        path: "docs/compliance",
        type: "directory",
        children: [
          { name: "PDPL_mapping.md", path: "docs/compliance/PDPL_mapping.md", type: "file", language: "markdown", size: "8.4 KB" },
          { name: "NCA_ECC_controls.md", path: "docs/compliance/NCA_ECC_controls.md", type: "file", language: "markdown", size: "5.6 KB" },
          { name: "NDMO_readiness.md", path: "docs/compliance/NDMO_readiness.md", type: "file", language: "markdown", size: "3.2 KB" },
        ],
      },
    ],
  },
  {
    name: ".github",
    path: ".github",
    type: "directory",
    children: [
      {
        name: "workflows",
        path: ".github/workflows",
        type: "directory",
        children: [
          { name: "ci.yml", path: ".github/workflows/ci.yml", type: "file", language: "yaml", size: "2.8 KB" },
          { name: "security-scan.yml", path: ".github/workflows/security-scan.yml", type: "file", language: "yaml", size: "1.4 KB" },
          { name: "pdpl-compliance.yml", path: ".github/workflows/pdpl-compliance.yml", type: "file", language: "yaml", size: "1.1 KB" },
        ],
      },
    ],
  },
  { name: "package.json", path: "package.json", type: "file", language: "json", size: "2.1 KB" },
  { name: "README.md", path: "README.md", type: "file", language: "markdown", size: "4.3 KB" },
  { name: "tsconfig.json", path: "tsconfig.json", type: "file", language: "json", size: "0.8 KB" },
];
