import type { PersonaPreset } from "@/forge/types";

export const personaPresets: PersonaPreset[] = [
  {
    key: "cto",
    name: "CTO / VP Engineering",
    shortLabel: "CTO",
    role: "Chief Technology Officer",
    icon: "Crown",
    sidebarSummary: "Portfolio health, strategic risk, release confidence",
    commandSummary: "See cross project health, risk posture, and compounding value across your portfolio",
    dashboardWidgets: ["portfolio-kpis", "release-confidence-trend", "proof-chain-gauge", "compounding-value", "governance-queue", "operate-incidents", "explainability-score"],
    metricPriorities: ["Release confidence", "Governance coverage", "Risk posture", "Pattern reuse rate"],
    notificationFilters: ["high-severity-approval", "release-ready", "risk-escalation"],
    actionPermissions: ["approve-releases", "view-evidence-packs", "manage-tenants"],
    memoryFeedOrder: ["Lesson learned", "Pattern reuse", "Evidence reuse", "Context link"],
    isCustom: false,
  },
  {
    key: "delivery-lead",
    name: "Delivery Lead",
    shortLabel: "Lead",
    role: "Delivery Lead",
    icon: "Workflow",
    sidebarSummary: "Assignments, velocity, gate pass rates, blockers",
    commandSummary: "Monitor story progression, velocity trends, and gate pass rates across the active project",
    dashboardWidgets: ["active-assignments", "phase-distribution", "story-spotlight", "governance-queue", "persona-metrics"],
    metricPriorities: ["Stories in flight", "Gate pass rate", "Blockers", "Days to release"],
    notificationFilters: ["gate-ready", "blocker-escalation", "story-overdue"],
    actionPermissions: ["advance-stories", "approve-gates", "assign-stories", "view-evidence-packs"],
    memoryFeedOrder: ["Lesson learned", "Context link", "Pattern reuse", "Evidence reuse"],
    isCustom: false,
  },
  {
    key: "solution-architect",
    name: "Solution Architect",
    shortLabel: "Architect",
    role: "Lead Solution Architect",
    icon: "Network",
    sidebarSummary: "Layer impact, dependency graph, design rationale",
    commandSummary: "Assess architecture impact across layers, review service boundaries, and validate design rationale",
    dashboardWidgets: ["architecture-impact", "cross-project-dependencies", "story-spotlight", "context-quality", "persona-metrics"],
    metricPriorities: ["Architecture coverage", "Dependency risk", "Design rationale completeness", "Pattern reuse rate"],
    notificationFilters: ["architecture-review-required", "dependency-conflict", "design-gate"],
    actionPermissions: ["approve-architecture-gates", "view-all-services", "create-design-evidence"],
    memoryFeedOrder: ["Pattern reuse", "Evidence reuse", "Context link", "Lesson learned"],
    isCustom: false,
  },
  {
    key: "developer",
    name: "Developer",
    shortLabel: "Dev",
    role: "Senior Software Engineer",
    icon: "Code2",
    sidebarSummary: "Active assignment, context quality, code review queue",
    commandSummary: "See your active stories, context quality score, and code review queue in one place",
    dashboardWidgets: ["active-assignments", "context-quality", "ci-pipeline-status", "story-spotlight", "persona-metrics", "execution-loop-status", "context-budget-gauge", "ide-connections"],
    metricPriorities: ["Context quality score", "CI pipeline status", "Active PR count", "Test coverage"],
    notificationFilters: ["pr-review-requested", "ci-failed", "context-ready"],
    actionPermissions: ["advance-to-test", "create-evidence", "view-context-hub"],
    memoryFeedOrder: ["Context link", "Pattern reuse", "Lesson learned", "Evidence reuse"],
    isCustom: false,
  },
  {
    key: "qa-lead",
    name: "QA Lead",
    shortLabel: "QA",
    role: "Quality Assurance Lead",
    icon: "CheckCircle2",
    sidebarSummary: "Test coverage, CI status, defect rate, release readiness",
    commandSummary: "Track test coverage trends, CI pipeline health, and release readiness across all active stories",
    dashboardWidgets: ["test-coverage-matrix", "ci-pipeline-status", "phase-distribution", "story-spotlight", "governance-queue"],
    metricPriorities: ["Test coverage", "Defect rate", "CI pass rate", "Release readiness"],
    notificationFilters: ["ci-failed", "coverage-drop", "test-gate-ready"],
    actionPermissions: ["approve-test-gates", "create-test-evidence", "view-ci-logs"],
    memoryFeedOrder: ["Lesson learned", "Evidence reuse", "Pattern reuse", "Context link"],
    isCustom: false,
  },
  {
    key: "security-officer",
    name: "Security Officer",
    shortLabel: "Security",
    role: "Chief Information Security Officer",
    icon: "Shield",
    sidebarSummary: "Vulnerability count, compliance gaps, control matrix",
    commandSummary: "Monitor security posture, active vulnerabilities, and control coverage across the portfolio",
    dashboardWidgets: ["security-scan-results", "compliance-dashboard", "governance-queue", "proof-chain-gauge", "persona-metrics", "operate-incidents"],
    metricPriorities: ["Open vulnerabilities", "Control coverage", "NCA ECC alignment", "Security gate pass rate"],
    notificationFilters: ["security-finding", "nca-gap", "security-gate-required"],
    actionPermissions: ["approve-security-gates", "view-all-evidence", "create-security-findings"],
    memoryFeedOrder: ["Evidence reuse", "Lesson learned", "Pattern reuse", "Context link"],
    isCustom: false,
  },
  {
    key: "compliance-officer",
    name: "Compliance Officer",
    shortLabel: "Compliance",
    role: "Data Protection and Compliance Officer",
    icon: "FileCheck",
    sidebarSummary: "PDPL alignment, evidence readiness, audit trail",
    commandSummary: "Track PDPL alignment, evidence completeness, and audit trail coverage across all projects",
    dashboardWidgets: ["compliance-dashboard", "governance-queue", "proof-chain-gauge", "persona-metrics", "active-assignments"],
    metricPriorities: ["PDPL coverage", "Evidence readiness", "Audit trail completeness", "Compliance gate pass rate"],
    notificationFilters: ["pdpl-gap", "evidence-missing", "compliance-gate"],
    actionPermissions: ["approve-compliance-gates", "export-evidence-packs", "view-audit-trail"],
    memoryFeedOrder: ["Evidence reuse", "Lesson learned", "Context link", "Pattern reuse"],
    isCustom: false,
  },
  {
    key: "product-owner",
    name: "Product Owner",
    shortLabel: "Product",
    role: "Product Owner",
    icon: "LayoutDashboard",
    sidebarSummary: "Story prioritization, requirement traceability, backlog health",
    commandSummary: "Prioritise the backlog, trace requirements to delivery, and track what is shipping in this release",
    dashboardWidgets: ["priority-matrix", "phase-distribution", "story-spotlight", "active-assignments", "persona-metrics"],
    metricPriorities: ["Stories ready for development", "Requirement coverage", "Backlog health", "Release scope completion"],
    notificationFilters: ["story-blocked", "scope-change", "release-ready"],
    actionPermissions: ["create-stories", "reprioritise-backlog", "approve-scope-gates"],
    memoryFeedOrder: ["Context link", "Lesson learned", "Pattern reuse", "Evidence reuse"],
    isCustom: false,
  },
  {
    key: "devops-lead",
    name: "DevOps Lead",
    shortLabel: "DevOps",
    role: "DevOps and Platform Engineering Lead",
    icon: "GitMerge",
    sidebarSummary: "Pipeline health, deployment frequency, connector status",
    commandSummary: "Monitor pipeline health, deployment frequency, and connector status across all active projects",
    dashboardWidgets: ["ci-pipeline-status", "cross-project-dependencies", "active-assignments", "persona-metrics", "cost-dashboard", "operate-incidents", "ide-connections"],
    metricPriorities: ["Deployment frequency", "Pipeline success rate", "Mean time to recovery", "Connector health"],
    notificationFilters: ["pipeline-failed", "deployment-event", "connector-issue"],
    actionPermissions: ["manage-connectors", "approve-deploy-gates", "view-infrastructure"],
    memoryFeedOrder: ["Pattern reuse", "Lesson learned", "Context link", "Evidence reuse"],
    isCustom: false,
  },
  {
    key: "programme-director",
    name: "Programme Director",
    shortLabel: "Director",
    role: "Programme Director",
    icon: "Briefcase",
    sidebarSummary: "Cross project status, milestone adherence, strategic risk",
    commandSummary: "See the full programme picture across projects, milestones, and strategic risk posture",
    dashboardWidgets: ["portfolio-kpis", "cross-project-dependencies", "compounding-value", "governance-queue", "release-confidence-trend"],
    metricPriorities: ["Programme milestone adherence", "Cross project risk", "Budget utilisation", "Stakeholder confidence"],
    notificationFilters: ["milestone-risk", "cross-project-dependency", "executive-approval"],
    actionPermissions: ["approve-programme-gates", "view-all-projects", "export-evidence-packs", "manage-tenants"],
    memoryFeedOrder: ["Lesson learned", "Pattern reuse", "Context link", "Evidence reuse"],
    isCustom: false,
  },
];
